name = "bse-gemini-resultanalyzer"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace Binding
[[kv_namespaces]]
binding = "BSE_GEMINI_DATA"
id = "6c86cb7981334c8ba2b1ed48d73e3d2a"

# Cron Trigger (Runs every minute)
[triggers]
crons = ["* * * * *"]